### ISSUE TITLE
Source code for ICELink

### ISSUE THREAD

**Issue by mamoit** [wuxx/icesugar#9]
Is the source code for `ICELink` open?
I can find it anywhere.
If not, is it a "not yet", or no plans on open sourcing it?
It is a great tool, but I'm having some weird intermittent problems after dragging in a new program.

**Comment by wuxx** [comment]
Hi，the souce code of iCELink will open in the future，and can you describe your problem in detail？

**Comment by mamoit** [comment]
I am sorry for the radio silence, it was an issue with Kubuntu 18.04, that when the board reset the old mount was kept behind, making it quite messy after a couple of iterations.
With Kubuntu 20.04 this does not happen anymore, so I think the issue can be overlooked.

Did you release the iCELink source? Or you decided not to?
(not judging here, I understand completely if you opt by not releasing it)

**Comment by wuxx** [comment]
iCELink source code currently has no open source plan, the firmware may be opened in future. :-)

**Comment by camrbuss** [comment]
Is there any plan to add features such as adjustable ICELink clock output on PA8? Is it fixed at 12MHz?

**Comment by wuxx** [comment]
the clock output will be able to adjust on iCESugar-nano board (base on ice40lp1k-cm36), because the lp1k-cm36 pll not support well by open source toolchain, current iCESugar seems not very necessary to have this feature ? it's pll can works well.
![QQ拼音截图未命名](https://user-images.githubusercontent.com/1648489/103399208-d8c7d400-4b7a-11eb-8477-199b55bf948d.png)
